version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  
  windows:
    executor:
      name: win/default
      size: "medium"
    steps:
      - checkout
      - run: choco install mingw
      - run: choco install cmake
      - run: refreshenv
      - run: SET PATH=%PATH%;"C:\Program Files\CMake\bin"
      - run: ECHO. Changed PATH is '%PATH%'
      - run: cmake

workflows:
  my-workflow:
    jobs:
      - windows