version: 2.1

orbs:
  win: circleci/windows@2.2.0
  cmake: sensu/cmake@1.0.0

jobs:
  
  windows:
    executor:
      name: win/default
      size: "medium"
    steps:
      - checkout
      - cmake/install
      - run: cmake

workflows:
  my-workflow:
    jobs:
      - windows